### ISSUE TITLE
Divergence of branches - problem with GetECMWF

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/Processing-SWAT#12]
There are currently two branches on processing_SWAT: **master** and **GW-A_dev**, the latter being a diverged version of the repository sent by email from @KittelC on 6 April 2016 to @ctottrup and added as-is as new branch.

The existence of two branches has caused problems: the latest PRs by @KittelC (#6, #7, and #8 submitted in June) were merged unto the **master** branch (see commit history [here](https://github.com/DHI-GRAS/processing_SWAT/commits/master)), even though the **GW-A_dev** branch presumably is the working version of @KittelC, if I am not mistaken?

I have now ported the mentioned PRs to the GW-A_dev branch, such that `ECMWFDataServer.py` and
`GetECMWFClimateData.py` are identical between the two branches. However, there is an error during execution (reported by @ctottrup):

```
2016-10-04T11:42:27 2 Uncaught error while executing algorithm
Traceback (most recent call last):
File "C:/Users/CTO/.qgis2/python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
self.processAlgorithm(progress)
File "C:/Users/CTO/.qgis2/python/plugins\processing_SWAT\OSFWF_GetECMWFData.py", line 111, in processAlgorithm
GetECMWFClimateData.ECMWFImport(email, token, start_date, end_date, tmax_dst_folder, tmin_dst_folder, left_long, right_long, top_lat, bottom_lat, progress)
File "C:/Users/CTO/.qgis2/python/plugins\processing_SWAT\GetECMWFClimateData.py", line 81, in ECMWFImport
GetECMWF(server, FirstYear, FirstMonth, FirstDay, LastYear, LastMonth, LastDay, LeftLon, RightLon, TopLat, BottomLat, dst_file)
File "C:/Users/CTO/.qgis2/python/plugins\processing_SWAT\GetECMWFClimateData.py", line 124, in GetECMWF
'target' : dst_file
File "C:/Users/CTO/.qgis2/python/plugins\processing_SWAT\ECMWFDataServer.py", line 442, in retrieve
c = Request(self.url, "datasets/%s" % (dataset,), self.email, self.key, self.trace, verbose = self.verbose)
File "C:/Users/CTO/.qgis2/python/plugins\processing_SWAT\ECMWFDataServer.py", line 327, in __init__
user = self.connection.call("%s/%s" % (self.url, "who-am-i"))
File "C:/Users/CTO/.qgis2/python/plugins\processing_SWAT\ECMWFDataServer.py", line 105, in wrapped
return func(*args,**kwargs)
File "C:/Users/CTO/.qgis2/python/plugins\processing_SWAT\ECMWFDataServer.py", line 277, in call
raise APIException("ecmwf.API error 1: %s" % (self.last["error"],) )
APIException: u'ecmwf.API error 1: Invalid or missing key or token' 
```

which is generated [here](https://github.com/DHI-GRAS/processing_SWAT/blob/0ab751576f51bd2be9d191d6e118e62fb67dcf6b/ECMWFDataServer.py#L248) and raised [here](https://github.com/DHI-GRAS/processing_SWAT/blob/0ab751576f51bd2be9d191d6e118e62fb67dcf6b/ECMWFDataServer.py#L277).
## Questions to you @KittelC
1. Is **GW-A_dev** your working version or are you actually working with **master**?
2. Are you experiencing the above mentioned error, too?
## Question to @ctottrup
1. What are the steps to reproduce this error?

**Comment by KittelC** [comment]
To answer the two questions: 
1. I am not currently working on either version and GW-A_dev was as I understood a way not to interfere with the TigerNet version untimely ( @ctottrup correct me if I am wrong).
1. I do not experience this issue - I just double checked running the code from QGIS on my machine using my email and the key retrieved as described on https://software.ecmwf.int/wiki/display/WEBAPI/Access+ECMWF+Public+Datasets - which also provides the ECMWFDataServer script.

**Comment by j08lue** [comment]
Thanks for the quick response, @KittelC! It turns out we used the wrong token, thanks for pointing me to the API instructions. With a token from https://api.ecmwf.int/v1/key/, ECMWF download works.

I will keep this thread open, because we will need to find out how to merge the two branches eventually, but the ECMWF download issue is solved.

**Comment by j08lue** [comment]
I will close this anyways. We can discuss merging branches if it ever becomes relevant.
