### ISSUE TITLE
Grass 6/7

### ISSUE THREAD

**Issue by KittelC** [TIGER-NET/Processing-SWAT#14]
It seems QGIS 2.18 no longer works with GRASS 6, however quite a few of the scripts use grass:r.mapcalculator, which is not supported by GRASS 7. Is there an alternative or work-around? Specifically, the climate data download workflows no longer work (e.g. GetECMFWClimateData etc.)...

**Comment by radosuav** [comment]
GRASS 6 should work in QGIS 2.18 but it is disabled by default. It needs to be activated in Processing > Options > Providers > GRASS commands. This should be taken care of if using the WOIS installer.

In the longer term (QGIS 3.x) GRASS 6 will no longer be supported. Possible workarounds would be to use OTB band math , GDAL raster calculator or (new in QGIS 3.x) Processing raster calculator.

**Comment by KittelC** [comment]
I have activated GRASS 6 (and checked it is installed) but I keep receiving an error message about GRASS not being installed properly when I try to run any GRASS 6 algorithm.. It seems like it is included but does not function.

**Comment by radosuav** [comment]
This usually indicates that GRASS paths are not set properly. Double check that the path set in Processing > Options > Providers > GRASS Commands > GRASS folder is correct. For example if you recently updated from GRASS 6.4.2 to 6.4.3 then this path needs to be modified.

**Comment by KittelC** [comment]
I have double checked the paths (including the msys path), but nothing seems to work (I also get a different error message than when something is up with the paths..)  - I have tried to update and reinstall GRASS 6 (and gone back to GRASS 6.4.2) without success... I've been using a numpy array approach instead for the ECMWF calculation which also works faster than mapcalculator, but it is really strange that GRASS 6 just doesn't work.. 

![capture](https://user-images.githubusercontent.com/8862587/26923880-d76a3a60-4c43-11e7-93fb-a90df16504ca.JPG)

**Comment by ctottrup** [comment]
and the GRASS 6 desktop application starts up with no problem?

**Comment by j08lue** [comment]
> This usually indicates that GRASS paths are not set properly.

That would be my guess, too. 

But you say it looks similar to this, @KittelC?

![image](https://user-images.githubusercontent.com/3404817/26924979-43de67b2-4c48-11e7-9a17-1fad020b9f60.png)

**Comment by KittelC** [comment]
Yes, mine is identical to this @j08lue 
@ctottrup - this might be the issue - when I try to run GRASS 6, I get a System Error: "gdal110.dll is missing from your computer. Try reinstalling the program to fix this problem". 
@radosuav this joins what you were writing in the other thread - that gdal might be the source of problem.

**Comment by KittelC** [comment]
I installed gdal110dll through advanced installation of OSGeo4w, and now the GRASS processing seems to work. It seems to have been a backwards compatibility issue, which is not automatically installed with OSGeo4w.

**Comment by j08lue** [comment]
https://github.com/TIGER-NET/WOIS_Installer/issues/26

**Comment by j08lue** [comment]
It seems like installing `gdal110dll` fixes the problem, @KittelC! 

I am checking some more installations to be all sure.

**Comment by j08lue** [comment]
Fixes the problem with WOIS package v4.2 on Windows 32 bit.

**Comment by j08lue** [comment]
And also on Windows 64 bit.
